server:
  port: 8080

spring.cloud.stream.kafka.binder:
  brokers: ${KAFKA_BROKER}
  defaultBrokerPort: ${KAFKA_PORT}

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "health"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${APP_EUREKA_USERNAME}:${APP_EUREKA_PASSWORD}@${APP_EUREKA_SERVER}:8761/eureka/