eureka:
  client:
    serviceUrl:
      defaultZone: http://u:p@localhost:8761/eureka/

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092