version: '3.9'

services:
  product:
    build: product

  recommendation:
    build: recommendation

  review:
    build: review

  composite-product:
    build: composite-product
    ports:
      - "8080:8080"
    environment:
      APP_PRODUCT_SERVICE_URL: product:8080
      APP_RECOMMENDATION_SERVICE_URL: recommendation:8080
      APP_REVIEW_SERVICE_URL: review:8080