spring:
  application:
    name: config-server

server.port: 8888

spring.cloud.config.server.native.searchLocations: file:/config-repo

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "health"

app:
  username: ${APP_CONFIG_SERVER_USERNAME}
  password: ${APP_CONFIG_SERVER_PASSWORD}
