server:
  port: 8082

spring.data.mongodb:
  host: localhost
  port: 27017
  database: recommendation-db

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://u:p@localhost:8761/eureka/