spring.cloud.gateway.routes:

  - id: composite-product
    uri: lb://composite-product
    predicates:
      - Path=/product-composite/**

  - id: composite-product-swagger-ui
    uri: lb://composite-product
    predicates:
      - Path=/openapi/**

  - id: eureka-api
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/api/{segment}
    filters:
      - SetPath=/eureka/{segment}

  - id: eureka-web-start
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/web
    filters:
      - SetPath=/

  - id: eureka-web-other
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://u:p@localhost:8761/eureka/
