apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config-map
data:
  MONGO_DB_URL: "mongodb-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  MYSQL_REVIEW_DATABASE: "review-db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config-map
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config-map
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgres-config-map
data:
  POSTGRES_DB: "keycloak"
  PGDATA: "/var/lib/postgresql/data/keycloak-pg-data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config-map
data:
  KC_DB: "postgres"
  KC_DB_URL_HOST: "keycloak-postgres-service"
  KC_DB_URL_DATABASE: "keycloak"
  KC_HTTP_RELATIVE_PATH: "/auth"
  KC_HOSTNAME: "mps.internal"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config-map
data:
  SPRING_CONFIG_LOCATION: "file:/config-repo/application.yml,file:/config-repo/product.yml"
  MONGO_PRODUCT_URL: "mongodb-service"
  MONGO_PRODUCT_DATABASE: "product-db"
  KAFKA_BROKER: "kafka-service"
  KAFKA_PORT: "9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-config-map
data:
  SPRING_CONFIG_LOCATION: "file:/config-repo/application.yml,file:/config-repo/recommendation.yml"
  MONGO_RECOMMENDATION_URL: "mongodb-service"
  MONGO_RECOMMENDATION_DATABASE: "recommendation-db"
  KAFKA_BROKER: "kafka-service"
  KAFKA_PORT: "9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: review-config-map
data:
  SPRING_CONFIG_LOCATION: "file:/config-repo/application.yml,file:/config-repo/review.yml"
  MYSQL_REVIEW_URL: "jdbc:mysql://mysql-service/review-db"
  KAFKA_BROKER: "kafka-service"
  KAFKA_PORT: "9092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: composite-product-config-map
data:
  SPRING_CONFIG_LOCATION: "file:/config-repo/application.yml,file:/config-repo/composite-product.yml"
  APP_KEYCLOAK_SERVER: "keycloak-service"
  APP_KEYCLOAK_REALM: "mps"
  KAFKA_BROKER: "kafka-service"
  KAFKA_PORT: "9092"