apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.2
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config-map
                  key: KC_DB
            - name: KC_DB_URL_HOST
              value: "keycloak-postgres-service"
            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config-map
                  key: KC_DB_URL_DATABASE
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: KC_HTTP_RELATIVE_PATH
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config-map
                  key: KC_HTTP_RELATIVE_PATH
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
          args: ["start-dev"]
          ports:
            - containerPort: 8080
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: keycloak-service
#spec:
#  type: NodePort
#  selector:
#    app: keycloak
#  ports:
#    - port: 80
#      targetPort: 8080
#      nodePort: 30443
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080