apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHB3ZA==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cHdk
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
type: Opaque
data:
  POSTGRES_USER: a2V5Y2xvYWs=
  POSTGRES_PASSWORD: a2V5Y2xvYWs=
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=