spring.cloud.config.server.native.searchLocations: C:\Users\patrick.oberkofler\Documents\GitHub\microservice-product-services\docker-compose\config-repo

app:
  username: u
  password: p

eureka:
  client:
    serviceUrl:
      defaultZone: http://u:p@localhost:8761/eureka/