spring.config.import: "configserver:"

spring:
  application.name: review
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    # URI localhost added for development
    uri: http://config-server:8888,http://localhost:8888
    username: u
    password: p