# Only required without Eureka-Server
#app:
#  productServiceUrl: localhost:8081
#  recommendationServiceUrl: localhost:8082
#  reviewServiceUrl: localhost:8083

server:
  port: 8099

springdoc:
  swagger-ui:
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
  oAuthFlow:
    authorizationUrl: http://localhost:8989/auth/realms/mps/protocol/openid-connect/auth
    tokenUrl: http://localhost:8989/auth/realms/mps/protocol/openid-connect/token

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8989/auth/realms/mps

