server:
  port: 8080

spring:
  application:
    name: gateway

spring.cloud.gateway.routes:

  - id: composite-product
    uri: lb://composite-product
    predicates:
      - Path=/product-composite/**

  - id: composite-product-swagger-ui
    uri: lb://composite-product
    predicates:
      - Path=/openapi/**

  - id: eureka-api
    uri: http://${APP_EUREKA_SERVER}:8761
    predicates:
      - Path=/eureka/api/{segment}
    filters:
      - SetPath=/eureka/{segment}

  - id: eureka-web-start
    uri: http://${APP_EUREKA_SERVER}:8761
    predicates:
      - Path=/eureka/web
    filters:
      - SetPath=/

  - id: eureka-web-other
    uri: http://${APP_EUREKA_SERVER}:8761
    predicates:
      - Path=/eureka/**

# If we want to access the config server from outside the landscape
#  - id: config-server
#    uri: http://${APP_CONFIG_SERVER_SERVER}:8888
#    predicates:
#      - Path=/config/**
#    filters:
#      - RewritePath=/config/(?<segment>.*), /$\{segment}

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${APP_KEYCLOAK_SERVER}/auth/realms/${APP_KEYCLOAK_REALM}
