spring.cloud.gateway.routes:

  - id: composite-product
    uri: lb://composite-product
    predicates:
      - Path=/product-composite/**

  - id: composite-product-swagger-ui
    uri: lb://composite-product
    predicates:
      - Path=/openapi/**

  - id: eureka-api
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/api/{segment}
    filters:
      - SetPath=/eureka/{segment}

  - id: eureka-web-start
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/web
    filters:
      - SetPath=/

  - id: eureka-web-other
    uri: http://localhost:8761
    predicates:
      - Path=/eureka/**

  - id: config-server
    uri: http://localhost:8888
    predicates:
      - Path=/config/**
    filters:
      - RewritePath=/config/(?<segment>.*), /$\{segment}

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8989/auth/realms/mps
