spring:
  application:
    name: product

spring.data.mongodb:
  host: ${MONGO_PRODUCT_URL}
  database: ${MONGO_PRODUCT_DATABASE}
  auto-index-creation: true

spring.cloud.function.definition: messageProcessor

spring.cloud.stream:
  defaultBinder: kafka
  bindings.messageProcessor-in-0:
    destination: products
    group: productsGroup

spring.cloud.stream.kafka.bindings.messageProcessor-in-0.consumer:
  enableDlq: true

spring.cloud.stream.bindings.messageProcessor-in-0.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0